name: CI

on: [ push, pull_request ]

env:
  NODE_VERSION: 16.x

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        env:
          CI: true

  lint-code:
    runs-on: ubuntu-latest
    needs: [ install ]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Lint
        run: npm run lint
        env:
          CI: true

  lint-commit-msg:
    runs-on: ubuntu-latest
    needs: [ install ]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Lint commit message
        run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
        env:
          CI: true

  test:
    runs-on: ubuntu-latest
    needs: [ install ]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Test
        run: npm run test
        env:
          CI: true

  build:
    runs-on: ubuntu-latest
    needs: [ install ]

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Build
        run: npm run build
        env:
          CI: true
